[Fix] ConcatDataset raise error when metainfo is np.array and is the same
When metainfo is N-dim np.array and is the same, the ConcatDataset will raise the following errors:

```
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

This is caused by the `!=` comparation of np.array